
analyzer:
   errors:
      public_member_api_docs: ignore
      lines_longer_than_80_chars: ignore
      avoid_catches_without_on_clauses: ignore
      inference_failure_on_untyped_parameter: ignore
      prefer_if_elements_to_conditional_expressions: ignore
   exclude: 
      - "**/*.g.dart"
      - "pubspec.yaml"
include: "package:very_good_analysis/analysis_options.yaml"

linter:
   rules:
 