name: spy_scanner
description: "Neon Apps - Spy Scanner - Final Project"
publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

    # UI
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.2

  #Routing
  auto_route: ^10.1.2

  # Localization
  easy_localization: ^3.0.8

  # Cache
  shared_preferences: ^2.5.3

  # Network Utils
  network_info_plus: ^7.0.0
  network_tools: ^6.0.5
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  # flutter_nsd: ^1.6.0
  nsd: ^4.0.3

  # Bluetooth
  flutter_reactive_ble: ^5.4.0

  # Utils
  path_provider: ^2.1.5
  get_it: ^8.2.0
  logging: ^1.3.0
  permission_handler: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Formatter  
  very_good_analysis: ^10.0.0

  # Test
  mockito: ^5.5.0

  #Code Gen
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/svg/