// Mocks generated by Mockito 5.4.6 from annotations
// in spy_scanner/test/services/payment_service_test/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pay/pay.dart' as _i2;
import 'package:pay_platform_interface/core/payment_configuration.dart' as _i4;
import 'package:pay_platform_interface/core/payment_item.dart' as _i5;
import 'package:spy_scanner/core/logging/error_handler.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Pay].
///
/// See the documentation for Mockito's code generation for more information.
class MockPay extends _i1.Mock implements _i2.Pay {
  MockPay() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> userCanPay(_i4.PayProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#userCanPay, [provider]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> showPaymentSelector(
    _i4.PayProvider? provider,
    List<_i5.PaymentItem>? paymentItems,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#showPaymentSelector, [provider, paymentItems]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> throwIfProviderIsNotDefined(_i4.PayProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#throwIfProviderIsNotDefined, [provider]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandler extends _i1.Mock implements _i6.ErrorHandler {
  MockErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T?> executeSafely<T>(
    _i3.Future<T> Function()? operation, {
    required String? errorMessage,
    _i3.FutureOr<void> Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeSafely,
              [operation],
              {#errorMessage: errorMessage, #onError: onError},
            ),
            returnValue: _i3.Future<T?>.value(),
          )
          as _i3.Future<T?>);
}
