// Mocks generated by Mockito 5.4.6 from annotations
// in spy_scanner/test/managers/blu_manager_test/ble_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i10;

import 'package:flutter_reactive_ble/src/discovered_devices_registry.dart'
    as _i2;
import 'package:flutter_reactive_ble/src/reactive_ble.dart' as _i3;
import 'package:logging/logging.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:reactive_ble_platform_interface/reactive_ble_platform_interface.dart'
    as _i5;
import 'package:spy_scanner/core/logging/custom_logger.dart' as _i7;
import 'package:spy_scanner/core/logging/error_handler.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscoveredDevicesRegistryImpl_0 extends _i1.SmartFake
    implements _i2.DiscoveredDevicesRegistryImpl {
  _FakeDiscoveredDevicesRegistryImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeCharacteristic_1 extends _i1.SmartFake
    implements _i3.Characteristic {
  _FakeCharacteristic_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiscoveredDevice_3 extends _i1.SmartFake
    implements _i5.DiscoveredDevice {
  _FakeDiscoveredDevice_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevel_4 extends _i1.SmartFake implements _i6.Level {
  _FakeLevel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterReactiveBle].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterReactiveBle extends _i1.Mock
    implements _i3.FlutterReactiveBle {
  MockFlutterReactiveBle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DiscoveredDevicesRegistryImpl get scanRegistry =>
      (super.noSuchMethod(
            Invocation.getter(#scanRegistry),
            returnValue: _FakeDiscoveredDevicesRegistryImpl_0(
              this,
              Invocation.getter(#scanRegistry),
            ),
          )
          as _i2.DiscoveredDevicesRegistryImpl);

  @override
  _i4.Stream<_i5.BleStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i4.Stream<_i5.BleStatus>.empty(),
          )
          as _i4.Stream<_i5.BleStatus>);

  @override
  _i5.BleStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i5.BleStatus.unknown,
          )
          as _i5.BleStatus);

  @override
  _i4.Stream<_i5.ConnectionStateUpdate> get connectedDeviceStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectedDeviceStream),
            returnValue: _i4.Stream<_i5.ConnectionStateUpdate>.empty(),
          )
          as _i4.Stream<_i5.ConnectionStateUpdate>);

  @override
  _i4.Stream<_i5.CharacteristicValue> get characteristicValueStream =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicValueStream),
            returnValue: _i4.Stream<_i5.CharacteristicValue>.empty(),
          )
          as _i4.Stream<_i5.CharacteristicValue>);

  @override
  _i5.LogLevel get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logLevel),
            returnValue: _i5.LogLevel.none,
          )
          as _i5.LogLevel);

  @override
  set logLevel(_i5.LogLevel? logLevel) => super.noSuchMethod(
    Invocation.setter(#logLevel, logLevel),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deinitialize() =>
      (super.noSuchMethod(
            Invocation.method(#deinitialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<int>> readCharacteristic(
    _i5.QualifiedCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristic, [characteristic]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<void> writeCharacteristicWithResponse(
    _i5.QualifiedCharacteristic? characteristic, {
    required List<int>? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristicWithResponse,
              [characteristic],
              {#value: value},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> writeCharacteristicWithoutResponse(
    _i5.QualifiedCharacteristic? characteristic, {
    required List<int>? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristicWithoutResponse,
              [characteristic],
              {#value: value},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> requestMtu({required String? deviceId, required int? mtu}) =>
      (super.noSuchMethod(
            Invocation.method(#requestMtu, [], {
              #deviceId: deviceId,
              #mtu: mtu,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> requestConnectionPriority({
    required String? deviceId,
    required _i5.ConnectionPriority? priority,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestConnectionPriority, [], {
              #deviceId: deviceId,
              #priority: priority,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.DiscoveredDevice> scanForDevices({
    required List<_i5.Uuid>? withServices,
    _i5.ScanMode? scanMode = _i5.ScanMode.balanced,
    bool? requireLocationServicesEnabled = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanForDevices, [], {
              #withServices: withServices,
              #scanMode: scanMode,
              #requireLocationServicesEnabled: requireLocationServicesEnabled,
            }),
            returnValue: _i4.Stream<_i5.DiscoveredDevice>.empty(),
          )
          as _i4.Stream<_i5.DiscoveredDevice>);

  @override
  _i4.Stream<_i5.ConnectionStateUpdate> connectToDevice({
    required String? id,
    Map<_i5.Uuid, List<_i5.Uuid>>? servicesWithCharacteristicsToDiscover,
    Duration? connectionTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [], {
              #id: id,
              #servicesWithCharacteristicsToDiscover:
                  servicesWithCharacteristicsToDiscover,
              #connectionTimeout: connectionTimeout,
            }),
            returnValue: _i4.Stream<_i5.ConnectionStateUpdate>.empty(),
          )
          as _i4.Stream<_i5.ConnectionStateUpdate>);

  @override
  _i4.Stream<_i5.ConnectionStateUpdate> connectToAdvertisingDevice({
    required String? id,
    required List<_i5.Uuid>? withServices,
    required Duration? prescanDuration,
    Map<_i5.Uuid, List<_i5.Uuid>>? servicesWithCharacteristicsToDiscover,
    Duration? connectionTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectToAdvertisingDevice, [], {
              #id: id,
              #withServices: withServices,
              #prescanDuration: prescanDuration,
              #servicesWithCharacteristicsToDiscover:
                  servicesWithCharacteristicsToDiscover,
              #connectionTimeout: connectionTimeout,
            }),
            returnValue: _i4.Stream<_i5.ConnectionStateUpdate>.empty(),
          )
          as _i4.Stream<_i5.ConnectionStateUpdate>);

  @override
  _i4.Future<List<_i5.DiscoveredService>> discoverServices(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#discoverServices, [deviceId]),
            returnValue: _i4.Future<List<_i5.DiscoveredService>>.value(
              <_i5.DiscoveredService>[],
            ),
          )
          as _i4.Future<List<_i5.DiscoveredService>>);

  @override
  _i4.Future<void> discoverAllServices(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#discoverAllServices, [deviceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.Service>> getDiscoveredServices(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoveredServices, [deviceId]),
            returnValue: _i4.Future<List<_i3.Service>>.value(<_i3.Service>[]),
          )
          as _i4.Future<List<_i3.Service>>);

  @override
  _i4.Future<void> clearGattCache(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#clearGattCache, [deviceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> readRssi(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#readRssi, [deviceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<List<int>> subscribeToCharacteristic(
    _i5.QualifiedCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToCharacteristic, [characteristic]),
            returnValue: _i4.Stream<List<int>>.empty(),
          )
          as _i4.Stream<List<int>>);

  @override
  _i4.Future<Iterable<_i3.Characteristic>> resolve(
    _i5.QualifiedCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolve, [characteristic]),
            returnValue: _i4.Future<Iterable<_i3.Characteristic>>.value(
              <_i3.Characteristic>[],
            ),
          )
          as _i4.Future<Iterable<_i3.Characteristic>>);

  @override
  _i4.Future<_i3.Characteristic> resolveSingle(
    _i5.QualifiedCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveSingle, [characteristic]),
            returnValue: _i4.Future<_i3.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(#resolveSingle, [characteristic]),
              ),
            ),
          )
          as _i4.Future<_i3.Characteristic>);
}

/// A class which mocks [CustomLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomLogger extends _i1.Mock implements _i7.CustomLogger {
  MockCustomLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void info(String? message) => super.noSuchMethod(
    Invocation.method(#info, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void warning(String? message) => super.noSuchMethod(
    Invocation.method(#warning, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void error(String? message, {Object? error, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {#error: error, #stackTrace: stackTrace},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message) => super.noSuchMethod(
    Invocation.method(#debug, [message]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandler extends _i1.Mock implements _i8.ErrorHandler {
  MockErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<T?> executeSafely<T>(
    _i4.Future<T> Function()? operation, {
    required String? errorMessage,
    _i4.FutureOr<void> Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeSafely,
              [operation],
              {#errorMessage: errorMessage, #onError: onError},
            ),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);
}

/// A class which mocks [StreamSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamSubscription<T> extends _i1.Mock
    implements _i4.StreamSubscription<T> {
  MockStreamSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);

  @override
  _i4.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onData(void Function(T)? handleData) => super.noSuchMethod(
    Invocation.method(#onData, [handleData]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Function? handleError) => super.noSuchMethod(
    Invocation.method(#onError, [handleError]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(void Function()? handleDone) => super.noSuchMethod(
    Invocation.method(#onDone, [handleDone]),
    returnValueForMissingStub: null,
  );

  @override
  void pause([_i4.Future<void>? resumeSignal]) => super.noSuchMethod(
    Invocation.method(#pause, [resumeSignal]),
    returnValueForMissingStub: null,
  );

  @override
  void resume() => super.noSuchMethod(
    Invocation.method(#resume, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<E> asFuture<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#asFuture, [futureValue]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#asFuture, [futureValue]),
                  ),
                  (E v) => _i4.Future<E>.value(v),
                ) ??
                _FakeFuture_2<E>(
                  this,
                  Invocation.method(#asFuture, [futureValue]),
                ),
          )
          as _i4.Future<E>);
}

/// A class which mocks [DiscoveredDevice].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDiscoveredDevice extends _i1.Mock implements _i5.DiscoveredDevice {
  MockDiscoveredDevice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  Map<_i5.Uuid, _i10.Uint8List> get serviceData =>
      (super.noSuchMethod(
            Invocation.getter(#serviceData),
            returnValue: <_i5.Uuid, _i10.Uint8List>{},
          )
          as Map<_i5.Uuid, _i10.Uint8List>);

  @override
  List<_i5.Uuid> get serviceUuids =>
      (super.noSuchMethod(
            Invocation.getter(#serviceUuids),
            returnValue: <_i5.Uuid>[],
          )
          as List<_i5.Uuid>);

  @override
  _i10.Uint8List get manufacturerData =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturerData),
            returnValue: _i10.Uint8List(0),
          )
          as _i10.Uint8List);

  @override
  int get rssi =>
      (super.noSuchMethod(Invocation.getter(#rssi), returnValue: 0) as int);

  @override
  _i5.Connectable get connectable =>
      (super.noSuchMethod(
            Invocation.getter(#connectable),
            returnValue: _i5.Connectable.unknown,
          )
          as _i5.Connectable);

  @override
  _i5.DiscoveredDevice copyWith({
    String? id,
    String? name,
    Map<_i5.Uuid, _i10.Uint8List>? serviceData,
    List<_i5.Uuid>? serviceUuids,
    _i10.Uint8List? manufacturerData,
    int? rssi,
    _i5.Connectable? connectable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #name: name,
              #serviceData: serviceData,
              #serviceUuids: serviceUuids,
              #manufacturerData: manufacturerData,
              #rssi: rssi,
              #connectable: connectable,
            }),
            returnValue: _FakeDiscoveredDevice_3(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #serviceData: serviceData,
                #serviceUuids: serviceUuids,
                #manufacturerData: manufacturerData,
                #rssi: rssi,
                #connectable: connectable,
              }),
            ),
          )
          as _i5.DiscoveredDevice);

  @override
  _i5.DiscoveredDevice copyUsing(
    void Function(_i5.DiscoveredDevice$Change)? mutator,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyUsing, [mutator]),
            returnValue: _FakeDiscoveredDevice_3(
              this,
              Invocation.method(#copyUsing, [mutator]),
            ),
          )
          as _i5.DiscoveredDevice);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i6.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  Map<String, _i6.Logger> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: <String, _i6.Logger>{},
          )
          as Map<String, _i6.Logger>);

  @override
  String get fullName =>
      (super.noSuchMethod(
            Invocation.getter(#fullName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#fullName),
            ),
          )
          as String);

  @override
  _i6.Level get level =>
      (super.noSuchMethod(
            Invocation.getter(#level),
            returnValue: _FakeLevel_4(this, Invocation.getter(#level)),
          )
          as _i6.Level);

  @override
  _i4.Stream<_i6.Level?> get onLevelChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onLevelChanged),
            returnValue: _i4.Stream<_i6.Level?>.empty(),
          )
          as _i4.Stream<_i6.Level?>);

  @override
  _i4.Stream<_i6.LogRecord> get onRecord =>
      (super.noSuchMethod(
            Invocation.getter(#onRecord),
            returnValue: _i4.Stream<_i6.LogRecord>.empty(),
          )
          as _i4.Stream<_i6.LogRecord>);

  @override
  set level(_i6.Level? value) => super.noSuchMethod(
    Invocation.setter(#level, value),
    returnValueForMissingStub: null,
  );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isLoggable(_i6.Level? value) =>
      (super.noSuchMethod(
            Invocation.method(#isLoggable, [value]),
            returnValue: false,
          )
          as bool);

  @override
  void log(
    _i6.Level? logLevel,
    Object? message, [
    Object? error,
    StackTrace? stackTrace,
    _i4.Zone? zone,
  ]) => super.noSuchMethod(
    Invocation.method(#log, [logLevel, message, error, stackTrace, zone]),
    returnValueForMissingStub: null,
  );

  @override
  void finest(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#finest, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void finer(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#finer, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void fine(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#fine, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void config(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#config, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void info(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#info, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void warning(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void severe(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#severe, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void shout(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#shout, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );
}
